version: '3.9'
services:
  postgres:
    image: postgres:17
    container_name: my_postgres_container
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST=${DB_HOST}
    ports:
      - "5433:5432"
    networks:
      - "backend-network"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_app_container
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - "backend-network"
    volumes:
      - ./src:/app/src
networks:
  backend-network:
    driver: bridge

volumes:
  postgres_data:
    name: postgres_data


