"""empty message

Revision ID: 704260707a61
Revises: 06750307ac38
Create Date: 2024-09-26 13:17:38.514968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '704260707a61'
down_revision: Union[str, None] = '06750307ac38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('main_machine',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('machine_name', sa.String(), nullable=False),
    sa.Column('startup_status', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('write_way', sa.String(), nullable=True),
    sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('loadfile_path', sa.String(), nullable=True),
    sa.Column('hot_reload', sa.String(), nullable=False),
    sa.Column('ready_ip', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('check_time', sa.Integer(), nullable=False),
    sa.Column('input_command', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('main_name',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('main_megacompila',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('value', sa.REAL(), nullable=True),
    sa.Column('get_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('analog', sa.Boolean(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('name_id', sa.BigInteger(), nullable=False),
    sa.Column('machine_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['main_machine.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['name_id'], ['main_name.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('main_name_machine',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('machine_id', sa.BigInteger(), nullable=False),
    sa.Column('name_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['main_machine.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['name_id'], ['main_name.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_id', 'machine_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('main_name_machine')
    op.drop_table('main_megacompila')
    op.drop_table('main_name')
    op.drop_table('main_machine')
    # ### end Alembic commands ###
